### ISSUE TITLE
Root Folders are not getting colorized

### ISSUE THREAD

**Issue by imabidin** [jacob-j/vscode-folder-path-color#20]
Hi,

am I doing something wrong, or why am I not able to colorize any root folders, like the highest folders in the Workspace? Subfolders are correctly displaying colors.

Any ideas? Thank you in advance.

![Screenshot 2024-01-07 105729](https://github.com/jacob-j/vscode-folder-path-color/assets/57065030/cd4d507f-b0a9-4b88-a0d6-adbb0d5b0e4a)

**Comment by GreenSmile** [comment]
I have the same issue. Try adding `../` before folder name in config.

For example:
```
{ "path": "../dev", "color": "yellow"}
```

**Comment by imabidin** [comment]
Thank you, it works!
